### PR TITLE
adding support for extra milight commands

### PR DESCRIPTION
**Pull request by alronz**

### CODE REVIEW

**Comment by alronz** [comment]
@stephenkeep I hope you have the time to look into this pull request. 
Thanks !

**Comment by stephenkeep** [comment]
Thanks for the pull request this looks good. I will push to NPM tonight.

**Comment by alronz** [comment]
Thanks @stephenkeep

**Comment by alronz** [comment]
@stephenkeep  it is still not published to npm. I would appreciate if you publish the current version, I get many request from people who are trying to access it since I have already deleted my node.

**Pull request merged**
