### PR TITLE
Add the command for changing the color temperature

### PR DESCRIPTION
**Pull request by rspaargaren**
In case a RGB WW/CW lamp is used the color temperature can be changed.
I have added the command temperature and by sending the value:
00 = 2700K (Warm White), 19 = 3650K, 32 = 4600K, 4B, = 5550K, 64 = 6500K (Cool White)
the temperature of whitelight changes.

### CODE REVIEW

**Comment by mwittig** [comment]
the if condition should be 

```
else if (command === 'temperature' && bulb === 'fullColor')
```

as the `whiteTemperature`command is supported for full color bulbs, only!

It would be nice if you could squash your commits into one commit

See https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git

**Comment by rspaargaren** [comment]
Hi mwittig tried to merge the commits but had to do it by command prompt on iPhone ... so I was limited. I added your remark to the Milight.js file

**Comment by rspaargaren** [comment]
As these changes are part of the pull request of rendmen the pull request can be rehected in case the other is committed

**Comment by mwittig** [comment]
As the author is not replying to e-mails and pending issues since months, I decided to spawn my fork as a new package: https://www.npmjs.com/package/node-red-contrib-milight-2

I am also planning to take care of the pending pull requests soon.

**Pull request closed without merging**
