### PR TITLE
Support for "v6" bridge including support for full color bulb and bridge light

### PR DESCRIPTION
**Pull request by mwittig**
* Support for "v6" bridge including support for full color bulb and bridge light,
* Refactoring: create Milight instance when node is created instead each time, when input is received (required for "v6" for performance reasons), 
* added support for effect modes (color bulb types, only), 
* allow for picking command from either msg.command or msg.topic, updated docs, 
* See also issue https://github.com/mwittig/node-milight-promise/issues/21

### CODE REVIEW

**Comment by mwittig** [comment]
* I have also added a new "rgb" command for color bulbs. This way it is possible, for example, to use MiLight along with a dashboard "Color Picker", for example. 
* I have dropped the special settings for `delayBetweenCommands` and `commandRepeat` as they did not work well in my test setups. A 50ms command delay is too agressive anyway as it'll likely produce package loss. That's what I have seen as part of my tests for node-milight-promise.
* I have tested the code with all supported bulb types and bridge types

**Comment by mwittig** [comment]
If you like this my contribution, please consider &#x2605; starring [the node-milight-promise project on github](https://github.com/mwittig/node-milight-promise). Thanks!

**Comment by alronz** [comment]
@stephenkeep this looks like a nice improvement to the node. If you don't have time to review it, please give me access and I can review, test and merge it.

**Comment by stephenkeep** [comment]
Thanks @alronz I have sent you a request as a collaborator

**Comment by mwittig** [comment]
@stephenkeep I am just wondering ... did you get my e-mail?

**Comment by mwittig** [comment]
As far as I know, several users are waiting for an update. 
The impatient may use my fork until a new release is available as follows:
1) Make sure you git installed on the system running node-red. 
2) Shutdown node-red
3) Run the following command using the same user account used for running node-red: `npm i mwittig/node-red-contrib-milight`
4) Start node-red

Later on, when the maintainer publishes a new release you can update to the new release via “Manage Palette”.

**Comment by alronz** [comment]
@mwittig  great work, thanks for your contribution.

**Comment by alronz** [comment]
@stephenkeep  could you please publish this to npm. I know many users who are waiting for it to be published. Thanks

**Pull request merged**
